Add a custom timeout in linux MR job

diff --git a/jenkinsfile/Jenkinsfile_MR_linux_cmake b/jenkinsfile/Jenkinsfile_MR_linux_cmake
--- a/jenkinsfile/Jenkinsfile_MR_linux_cmake
+++ b/jenkinsfile/Jenkinsfile_MR_linux_cmake
@@ -37,6 +37,8 @@ def setCommitStatus(String pStatus, String errorHint = '') {
     updateGitlabCommitStatus(name: "${PIPELINE_NAME}", state: pState)
 }
 
+def CUSTOM_TIMEOUT
+
 pipeline {
     agent none
     options {
@@ -81,10 +83,13 @@ pipeline {
                                     TESTS_PARALLEL = sh(script: 'echo "$gitlabTriggerPhrase" | grep "\\-\\-sequence" >/dev/null 2>&1 && echo "" || echo "--INSTANCES:10"', returnStdout: true).trim()
                                     GTEST_REPEAT = sh(script: 'echo "$gitlabTriggerPhrase" | grep --only-matching "\\-\\-gtest_repeat=[^ ]*" | awk -F "gtest_repeat="  \'{print "--gtest_repeat="\$2}\'|| :', returnStdout: true).trim()
                                     GTEST_FILTER = sh(script: 'echo "$gitlabTriggerPhrase" | grep --only-matching "\\-\\-gtest_filter=[^ ]*" | awk -F "gtest_filter="  \'{print "--gtest_filter="\$2}\'|| :', returnStdout: true).trim()
+                                    CUSTOM_TIMEOUT = sh(script: 'echo "$gitlabTriggerPhrase" | grep --only-matching "\\-\\-timeout=[^ ]*" | awk -F "timeout="  \'{print \$2}\'|| :', returnStdout: true).trim()
+                                    CUSTOM_TIMEOUT = CUSTOM_TIMEOUT? CUSTOM_TIMEOUT : "120"
                                     println BUILD_OPTIONS
                                     println TESTS_PARALLEL
                                     println GTEST_REPEAT
                                     println GTEST_FILTER
+                                    println CUSTOM_TIMEOUT
                                 }
                             }
                         }
@@ -163,9 +168,6 @@ pipeline {
                     }
                 }
                 stage('Run Linux tests'){
-                    options{
-                        timeout(time: 250, unit: 'MINUTES')
-                    }
                     environment {
                         MEGA_PWD = credentials('MEGA_PWD_DEFAULT')
                         MEGA_PWD_AUX = credentials('MEGA_PWD_DEFAULT')
@@ -174,108 +176,110 @@ pipeline {
                         BUILD_DIR = "build_dir"
                     }
                     steps{
-                        script {
-                            def lockLabel = ''
-                            if ("${APIURL_TO_TEST}" == 'https://g.api.mega.co.nz/') {
-                                lockLabel = 'SDK_Concurrent_Test_Accounts'
-                            } else  {
-                                lockLabel = 'SDK_Concurrent_Test_Accounts_Staging'
-                            }
-                            lock(label: lockLabel, variable: 'ACCOUNTS_COMBINATION', quantity: 1, resourceSelectStrategy: "random", resource: null){
-                                dir("${linux_sources_workspace}") {
-                                    script{
-                                        env.MEGA_EMAIL = "${env.ACCOUNTS_COMBINATION}"
-                                        echo "${env.ACCOUNTS_COMBINATION}"
-                                    }
-                                    sh "echo Running tests"
-                                    sh """#!/bin/bash
-                                    set -x
-                                    ulimit -c unlimited
+                        timeout(time: "${CUSTOM_TIMEOUT}", unit: 'MINUTES') {
+                            script {
+                                def lockLabel = ''
+                                if ("${APIURL_TO_TEST}" == 'https://g.api.mega.co.nz/') {
+                                    lockLabel = 'SDK_Concurrent_Test_Accounts'
+                                } else  {
+                                    lockLabel = 'SDK_Concurrent_Test_Accounts_Staging'
+                                }
+                                lock(label: lockLabel, variable: 'ACCOUNTS_COMBINATION', quantity: 1, resourceSelectStrategy: "random", resource: null){
+                                    dir("${linux_sources_workspace}") {
+                                        script{
+                                            env.MEGA_EMAIL = "${env.ACCOUNTS_COMBINATION}"
+                                            echo "${env.ACCOUNTS_COMBINATION}"
+                                        }
+                                        sh "echo Running tests"
+                                        sh """#!/bin/bash
+                                        set -x
+                                        ulimit -c unlimited
 
-                                    ${env.BUILD_DIR}/tests/unit/test_unit || FAILED=1
+                                        ${env.BUILD_DIR}/tests/unit/test_unit || FAILED=1
 
-                                    if [ -z \"\$FAILED\" ]; then
-                                        GFXWORKER_TEST_DIR=${env.BUILD_DIR}/tools/gfxworker/tests/integration/
-                                        GFXWORKER_TEST_NAME=gfxworker_test_integration
-                                        GFXWORKER_TEST_PATH=\"\$GFXWORKER_TEST_DIR\$GFXWORKER_TEST_NAME\"
-                                        if [ -f \"\$GFXWORKER_TEST_PATH\" ]; then
-                                            \$GFXWORKER_TEST_PATH || FAILED=2
-                                            gzip -c gfxworker_test_integration.log > gfxworker_test_integration_${BUILD_ID}.log.gz || :
-                                            rm gfxworker_test_integration.log || :
-                                        fi
-                                    fi
-
-                                    if [ -z \"\$FAILED\" ]; then
-                                        if [ -z \"${TESTS_PARALLEL}\" ]; then
-                                            # Sequential run
-                                            ${env.BUILD_DIR}/tests/integration/test_integration --FREEACCOUNTS --CI --USERAGENT:${env.USER_AGENT_TESTS_SDK} --APIURL:${APIURL_TO_TEST} ${GTEST_FILTER} ${GTEST_REPEAT} &
-                                            pid=\$!
-                                            wait \$pid || FAILED=3
-                                            if [ \"\$FAILED\" = \"3\" ]; then
-                                                cp ${linux_sources_workspace}/pid_\$pid/test_integration.log .
+                                        if [ -z \"\$FAILED\" ]; then
+                                            GFXWORKER_TEST_DIR=${env.BUILD_DIR}/tools/gfxworker/tests/integration/
+                                            GFXWORKER_TEST_NAME=gfxworker_test_integration
+                                            GFXWORKER_TEST_PATH=\"\$GFXWORKER_TEST_DIR\$GFXWORKER_TEST_NAME\"
+                                            if [ -f \"\$GFXWORKER_TEST_PATH\" ]; then
+                                                \$GFXWORKER_TEST_PATH || FAILED=2
+                                                gzip -c gfxworker_test_integration.log > gfxworker_test_integration_${BUILD_ID}.log.gz || :
+                                                rm gfxworker_test_integration.log || :
                                             fi
-                                        else
-                                            # Parallel run
-                                            ${env.BUILD_DIR}/tests/integration/test_integration --FREEACCOUNTS --CI --USERAGENT:${env.USER_AGENT_TESTS_SDK} --APIURL:${APIURL_TO_TEST} ${GTEST_FILTER} ${GTEST_REPEAT} ${TESTS_PARALLEL} 2>&1 | tee tests.stdout
-                                            [ \"\${PIPESTATUS[0]}\" != \"0\" ] && FAILED=3
                                         fi
-                                    fi
-                                    if [ -n \"\$FAILED\" ]; then
-                                        if [ \"\$FAILED\" -le 2 ]; then
-                                            coreFiles=core
-                                        else # FAILED=3
+
+                                        if [ -z \"\$FAILED\" ]; then
                                             if [ -z \"${TESTS_PARALLEL}\" ]; then
                                                 # Sequential run
-                                                coreFiles=\"pid_\$pid/core\"
+                                                ${env.BUILD_DIR}/tests/integration/test_integration --FREEACCOUNTS --CI --USERAGENT:${env.USER_AGENT_TESTS_SDK} --APIURL:${APIURL_TO_TEST} ${GTEST_FILTER} ${GTEST_REPEAT} &
+                                                pid=\$!
+                                                wait \$pid || FAILED=3
+                                                if [ \"\$FAILED\" = \"3\" ]; then
+                                                    cp ${linux_sources_workspace}/pid_\$pid/test_integration.log .
+                                                fi
                                             else
                                                 # Parallel run
-                                                procFailed=`grep \"<< PROCESS\" tests.stdout | sed 's/.*PID:\\([0-9]*\\).*/\\1/'`
-                                                if [ -n \"\$procFailed\" ]; then
+                                                ${env.BUILD_DIR}/tests/integration/test_integration --FREEACCOUNTS --CI --USERAGENT:${env.USER_AGENT_TESTS_SDK} --APIURL:${APIURL_TO_TEST} ${GTEST_FILTER} ${GTEST_REPEAT} ${TESTS_PARALLEL} 2>&1 | tee tests.stdout
+                                                [ \"\${PIPESTATUS[0]}\" != \"0\" ] && FAILED=3
+                                            fi
+                                        fi
+                                        if [ -n \"\$FAILED\" ]; then
+                                            if [ \"\$FAILED\" -le 2 ]; then
+                                                coreFiles=core
+                                            else # FAILED=3
+                                                if [ -z \"${TESTS_PARALLEL}\" ]; then
+                                                    # Sequential run
+                                                    coreFiles=\"pid_\$pid/core\"
+                                                else
                                                     # Parallel run
-                                                    for i in \$procFailed; do
-                                                        coreFiles=\"\$coreFiles pid_\$i/core\"
+                                                    procFailed=`grep \"<< PROCESS\" tests.stdout | sed 's/.*PID:\\([0-9]*\\).*/\\1/'`
+                                                    if [ -n \"\$procFailed\" ]; then
+                                                        # Parallel run
+                                                        for i in \$procFailed; do
+                                                            coreFiles=\"\$coreFiles pid_\$i/core\"
+                                                        done
+                                                    fi
+                                                fi
+                                            fi
+                                            if [ -n \"\$coreFiles\" ]; then
+                                                maxTime=10
+                                                startTime=`date +%s`
+                                                coresProcessed=0
+                                                coresTotal=`echo \$coreFiles | wc -w`
+                                                # While there are pending cores
+                                                while [ \$coresProcessed -lt \$coresTotal ] && [ \$( expr `date +%s` - \$startTime ) -lt \$maxTime ]; do
+                                                    echo "Waiting for core dumps..."
+                                                    sleep 1
+                                                    for i in \$coreFiles; do
+                                                        if [ -e \"\$i\" ] && [ -z \"\$( lsof \$i 2>/dev/null )\" ]; then
+                                                            echo \"Processing core dump \$i :: \$(grep `echo \$i | sed 's#pid_\\([0-9].*\\)/core#\\1#'` tests.stdout)\"
+                                                            echo thread apply all bt > backtrace
+                                                            echo quit >> backtrace
+                                                            [ \"\$FAILED\" = \"1\" ] && gdb -q ${env.BUILD_DIR}/tests/unit/test_unit \$i -x backtrace
+                                                            [ \"\$FAILED\" = \"2\" ] && gdb -q \$GFXWORKER_TEST_PATH \$i -x backtrace
+                                                            [ \"\$FAILED\" = \"3\" ] && gdb -q ${env.BUILD_DIR}/tests/integration/test_integration \$i -x backtrace
+                                                            tar rf core.tar \$i
+                                                            coresProcessed=`expr \$coresProcessed + 1`
+                                                            coreFiles=`echo \$coreFiles | sed -e \"s#\$i##\"`
+                                                        fi
                                                     done
+                                                done
+                                                if [ -e core.tar ]; then
+                                                    [ \"\$FAILED\" = \"1\" ] && tar rf core.tar -C ${env.BUILD_DIR}/tests/unit/ test_unit
+                                                    [ \"\$FAILED\" = \"2\" ] && tar rf core.tar -C \$GFXWORKER_TEST_DIR \$GFXWORKER_TEST_NAME
+                                                    [ \"\$FAILED\" = \"3\" ] && tar rf core.tar -C ${env.BUILD_DIR}/tests/integration/ test_integration
+                                                    gzip core.tar
                                                 fi
                                             fi
                                         fi
-                                        if [ -n \"\$coreFiles\" ]; then
-                                            maxTime=10
-                                            startTime=`date +%s`
-                                            coresProcessed=0
-                                            coresTotal=`echo \$coreFiles | wc -w`
-                                            # While there are pending cores
-                                            while [ \$coresProcessed -lt \$coresTotal ] && [ \$( expr `date +%s` - \$startTime ) -lt \$maxTime ]; do
-                                                echo "Waiting for core dumps..."
-                                                sleep 1
-                                                for i in \$coreFiles; do
-                                                    if [ -e \"\$i\" ] && [ -z \"\$( lsof \$i 2>/dev/null )\" ]; then
-                                                        echo \"Processing core dump \$i :: \$(grep `echo \$i | sed 's#pid_\\([0-9].*\\)/core#\\1#'` tests.stdout)\"
-                                                        echo thread apply all bt > backtrace
-                                                        echo quit >> backtrace
-                                                        [ \"\$FAILED\" = \"1\" ] && gdb -q ${env.BUILD_DIR}/tests/unit/test_unit \$i -x backtrace
-                                                        [ \"\$FAILED\" = \"2\" ] && gdb -q \$GFXWORKER_TEST_PATH \$i -x backtrace
-                                                        [ \"\$FAILED\" = \"3\" ] && gdb -q ${env.BUILD_DIR}/tests/integration/test_integration \$i -x backtrace
-                                                        tar rf core.tar \$i
-                                                        coresProcessed=`expr \$coresProcessed + 1`
-                                                        coreFiles=`echo \$coreFiles | sed -e \"s#\$i##\"`
-                                                    fi
-                                                done
-                                            done
-                                            if [ -e core.tar ]; then
-                                                [ \"\$FAILED\" = \"1\" ] && tar rf core.tar -C ${env.BUILD_DIR}/tests/unit/ test_unit
-                                                [ \"\$FAILED\" = \"2\" ] && tar rf core.tar -C \$GFXWORKER_TEST_DIR \$GFXWORKER_TEST_NAME
-                                                [ \"\$FAILED\" = \"3\" ] && tar rf core.tar -C ${env.BUILD_DIR}/tests/integration/ test_integration
-                                                gzip core.tar
-                                            fi
-                                        fi
-                                    fi
 
-                                    gzip -c test_integration.log > test_integration_${BUILD_ID}.log.gz || :
-                                    rm test_integration.log || :
-                                    if [ -n \"\$FAILED\" ]; then
-                                        exit \"\$FAILED\"
-                                    fi
-                                    """
+                                        gzip -c test_integration.log > test_integration_${BUILD_ID}.log.gz || :
+                                        rm test_integration.log || :
+                                        if [ -n \"\$FAILED\" ]; then
+                                            exit \"\$FAILED\"
+                                        fi
+                                        """
+                                    }
                                 }
                             }
                         }
